# Generated by Django 3.2.9 on 2021-11-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user_bayer',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='bayer_archive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth_user.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='brand_name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='category',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='id_product_archive',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='model',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='warranty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
